---
- name: Generate switch configuration files
  template: src=C5E3access_switch.j2 dest=/home/seremetkoski/pynet_brutal/class5/C5E3/roles/switches/{{item.hostname}}.txt
  with_items: '{{access_switch}}'
