---
- hosts: local
  vars:
    hostname: pynet-rtr1
  tasks:
    - name: Generate configuration file
      template: src=/home/seremetkoski/pynet_brutal/class5/router1.j2
                  dest=/home/seremetkoski/pynet_brutal/class5/router1.txt

