---

- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: Setting Ethernet4 description
      eos_interface: name=Ethernet4 description="*** TESTING VID2 ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Set Ethernet2-4 to access mode, VLAN200
      eos_switchport: name={{ item }} mode=access access_vlan=200
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
            - Ethernet2
            - Ethernet3
            - Ethernet4
